# [unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "compiler_builtins"]

[build]
target = "armv7a-none-eabi"
# target = "arm_32-zero.json"
# target = "thumbv6m-none-eabi"
